import 'package:hive/hive.dart';

part 'everything_source.g.dart'; // This is generated by the build_runner

@HiveType(typeId: 0)
class EverythingSourceModelData extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String name;

  EverythingSourceModelData({
    required this.id,
    required this.name,
  });
}
